### ISSUE TITLE
Test: Endpoints for blog posts

### ISSUE THREAD

**Issue by mikewheel** [mikewheel/blog#2]
### Goal
Design, implement, and deploy a serverless blog in AWS.

### Objective
Write failing unit end-to-end tests on the blog's API endpoints (API Gateway).

### Tasks
Unauthenticated:
  - [ ]  `GET /{slug}`: 200 w HTML body: rendered blog post content
  - [ ]  `GET /tagged/{tag}: 200 w HTML body: rendered search results
  - [ ]  `GET /api/tags`: 200 w JSON body: sorted list of post titles and urls, hopefully paginated

Authenticated (JSON):
  - [ ]  `GET /api/blog-posts` 200 w JSON body: blog post content
  - [ ]  `POST /api/blog-posts` 200 w JSON body: URL to HTML -> appears
  - [ ]  `PUT /api/blog-posts` apply updates to blog post all at once, changes appear on GET and HTML
  - [ ]  `DELETE /api/blog-posts` removes post, does not appear on GET nor on HTML
